config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # get '/auth/wix', to: 'oauth#wix_auth'
  get '/auth/wix/callback' => 'authentications#create'
  post '/auth/wix/callback' => 'authentications#create'
  get '/auth/wix' => 'authentications#blank'
  # get '/oauth/callback', to: 'oauth#wix_callback'
  # get '/oauth/authorize', to: 'oauth#authorize'
  post '/webhook', to: 'orders#webhook'

  resources :projects
  resources :orders
  resources :shops do
    member do
      get 'import_orders'
      get 'import_projects'
    end
  end
  root 'shops#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/authentication.rb
class Authentication < ApplicationRecord
  has_one :shop, dependent: :destroy

  validates :uid, uniqueness: true
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_line_items
end

app/models/order_line_item.rb
class OrderLineItem < ApplicationRecord
  belongs_to :order
  belongs_to :project
end

app/models/project.rb
class Project < ApplicationRecord
  validates :external_reference_id, uniqueness: true
end

app/models/shop.rb
class Shop < ApplicationRecord
  belongs_to :authentication
  validates :external_shop_id, uniqueness: true

  def is_token_active?
    self.authentication.token_expires_at.future?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/authentications_controller.rb
class AuthenticationsController < ApplicationController
  def create
    process_wix_install

    redirect_to shops_path, notice: "Shop was successfully created."
  end

  def blank
    # Wix can be installed via the Wix App Market which redirects here via GET, so we need to catch it and redirect via POST
    repost("/auth/wix", params: { provider: "wix", token: params[:token] }, options: { authenticity_token: :auto }) and return
  end

  private

  def omniauth
    request.env["omniauth.auth"]
  end

  def process_wix_install
    auth = omniauth

    wix_instance_id = auth.uid
    access_token = auth.credentials.token
    email = auth.info.email
    site_url = auth.info.site_url

    # Store or update the Wix shop/app installation in your DB
    authentication = Authentication.find_or_initialize_by(uid: wix_instance_id)

    if authentication.new_record?
      authentication.update!(
        token: auth.credentials.token,
        refresh_token: auth.credentials.refresh_token
      )

      shop = Shop.where(external_shop_id: auth.extra.raw_info.site_id).first_or_initialize

      if shop.new_record?
        shop.update(name: auth.extra.raw_info.site_display_name, url: auth.extra.raw_info.url, authentication_id: authentication.id)
      end
    end
  end
end

app/controllers/oauth_controller.rb
class OauthController < ApplicationController
  def wix_auth
    redirect_to WixService.new.auth_url
  end

  def wix_callback
    if params[:token]
      redirect_to WixService.new.install_url(params[:token])
    end
  end

  def authorize
    if params[:code]
      authorization_code = params[:code]
      successful = WixService.new.exchange_code_for_token(authorization_code)

      if successful
        redirect_to root_path, notice: "Successfully connected to Wix!"
      else
        redirect_to root_path, notice: "Not successful"
      end
    end
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  skip_before_action :verify_authenticity_token, only: [:webhook]

  def index
    @orders = Order.all
  end

  def import_orders
    WixService.new.get_orders(Shop.first)

    redirect_to orders_path
  end

  def webhook
    begin
      payload = JWT.decode(request.raw_post, OpenSSL::PKey::RSA.new(ENV['WIX_PUBLIC_KEY']), true, algorithm: 'RS256').first

      event = JSON.parse(payload['data'])
      event_data = JSON.parse(event['data'])

      case event['eventType']
      when "wix.ecom.v1.order_updated"
        order = Order.find_by(external_reference_id: event_data['updatedEvent']['currentEntity']['id'])

        if order.present?
          # changing status of the order
          order.update(status: event_data['updatedEvent']['currentEntity']['fulfillmentStatus'],
            payment_status: event_data['updatedEvent']['currentEntity']['paymentStatus'])
        end
  
        Rails.logger.info("OrderUpdated event received: #{event_data}")
        Rails.logger.info("Instance ID: #{event['instanceId']}")
      else
        Rails.logger.warn("Unknown event type received: #{event['eventType']}")
      end

      head :ok
    rescue => e
      Rails.logger.error("Webhook error: #{e.message}")
      render plain: "Webhook error: #{e.message}", status: :bad_request
    end
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @projects = Project.all
  end
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  def index
    @shops = Shop.all
  end

  def show
    @shop = Shop.find(params[:id])
  end

  def import_orders
    @shop = Shop.find(params[:id])
    WixService.new(@shop).get_orders

    redirect_to orders_path
  end

  def import_projects
    @shop = Shop.find(params[:id])
    WixService.new(@shop).get_products

    redirect_to projects_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authentication_helper.rb
module AuthenticationHelper
end

app/helpers/oauth_helper.rb
module OauthHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WixIntegration</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "shared/nav_bar" %>
    <div class="body-content">
      <% if flash[:notice] %>
        <p class="notice"><%= flash[:notice] %></p>
      <% end %>
      <% if flash[:alert] %>
        <p class="alert"><%= flash[:alert] %></p>
      <% end %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/orders/index.html.erb
<h2>Orders</h2>

<table>
  <tr>
    <th>External ID</th>
    <th> Line Item Count </th>
    <th> Fullfillment Status </th>
    <th> Payment Status </th>
    <th>Total</th>
  </tr>
  <% @orders.each do |order| %>
    <tr>
      <td> <%= order.external_reference_id %> </td>
      <td> <%= order.order_line_items.count %> </td>
      <td> <%= order.status %> </td>
      <td> <%= order.payment_status %> </td>
      <td> <%= order.total %> </td>
    </tr>
  <% end %>
</table>

app/views/projects/index.html.erb
<h2>Projects</h2>

<table>
  <tr>
    <th>Name</th>
    <th>SKU</th>
    <th>Description</th>
    <th>Product Type</th>
    <th>Price</th>
  </tr>
  <% @projects.each do |project| %>
    <tr>
      <td> <%= project.name %> </td>
      <td> <%= project.sku %> </td>
      <td> <%= project.description %> </td>
      <td> <%= project.product_type %> </td>
      <td> <%= "#{project.currency} #{project.price}" %> </td>
    </tr>
  <% end %>
</table>

app/views/shared/_nav_bar.html.erb
<ul class="navbar">
  <%= link_to "Home", '/', class: "navbar-li" %>
  <%= link_to "Shops", shops_path, class: "navbar-li #{'active' if current_page?(shops_path)}" %>
  <%= link_to "Products", projects_path, class: "navbar-li #{'active' if current_page?(projects_path)}" %>
  <%= link_to "Orders", orders_path, class: "navbar-li #{'active' if current_page?(orders_path)}" %>
</ul>

app/views/shops/index.html.erb
<div class="container">
  <div>
    <h2>Wix Shops</h2>
  </div
  <div>
    <div class="right-buttons">
      <%= link_to "Connect to Wix", '/auth/wix', class: "button" %>
    </div>
  </div
</div>

<table>
  <tr>
    <th> Name</th>
    <th> Created Date </th>
  </tr>
  <% @shops.each do |shop| %>
    <tr>
      <td> <%= link_to shop.name, shop_path(shop) %> </td>
      <td> <%= shop.created_at %> </td>
    </tr>
  <% end %>
</table>

app/views/shops/show.html.erb
<div class="container">
  <div>
    <table>
      <tr>
        <td>
          Shop Name:
        </td>
        <td>
          <%= @shop.name %>
        </td>
      </tr>
      <tr>
        <td>
          Description:
        </td>
        <td>
          <%= @shop.description ?  @shop.description : 'N/A' %>
        </td>
      </tr>
      <tr>
        <td>
          URL:
        </td>
        <td>
          <%= @shop.url ? @shop.url : "N/A" %>
        </td>
      </tr>
      <tr>
        <td>
          Shop ID:
        </td>
        <td>
          <%= @shop.external_shop_id %>
        </td>
      </tr>
      <tr>
        <td>
          Type:
        </td>
        <td>
          Wix
        </td>
      </tr>
      <tr>
        <td>
          Created Date:
        </td>
        <td>
          <%= @shop.created_at %>
        </td>
      </tr>
    </table>
  </div>
  <div>
    <div class="right-buttons">
      <%= link_to "Import Projects", import_projects_shop_path(@shop.id), class: "button" %>
      <%= link_to "Import Orders", import_orders_shop_path(@shop.id), class: "button" %>
    </div>
  </div>
</div>